package com.qa.project.persistence.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/*
 * This class AgentDomain is used to represent an 'agent' record in the database table. 
 * The class is annotated as JPA Entity, which is used to define the mapping between the 
 * class and the database table. The class also has private fields that are annotated 
 * with @Column annotation which is used to map the fields to the corresponding columns 
 * in the table. The field id is annotated with @Id and @GeneratedValue(strategy = GenerationType.IDENTITY) 
 * this is used to indicate that the field is primary key and the value will be generated by the database. 
 */

@Entity // indicates that this class is a JPA entity
@Table(name = "agent") // maps the class to a database table named "agent"
public class AgentDomain {
	
	@Id // Sets the variable to be the primary key
	@GeneratedValue(strategy = GenerationType.IDENTITY) // Auto-Increments for us
	@Column(name = "agent_id") // maps the field to a column named "agent_id"
	private Long id;
	
	@Column(name = "first_name")
	private String firstName;
	
	@Column(name = "surname")
	private String surname;
	
	@Column(name = "phone")
	private String phone;
	
	// default constructor
	public AgentDomain() {
		super();
	}
	
	// all arguments constructor
	public AgentDomain(Long id, String firstName, String surname, String phone) {
		super();
		this.id = id;
		this.firstName = firstName;
		this.surname = surname;
		this.phone = phone;
	}
	
	// getters and setters

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getSurname() {
		return surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

}
